### ISSUE TITLE
Line Protocol Support?

### ISSUE THREAD

**Issue by hl68fx** [mblackstock/node-red-contrib-influxdb#2]
Hi Mike,

first of all thank you very much for your influxd node.
I would like to ask if it is supporting the influxdb line protocol? I have got everything to work but only when I format the data I am sending from my microcontroller as JSON. Then I have to put a JSON node between my receiving node and the influxdb node.
As I am a complete beginner it could be that I am doing something wrong.

Kind regards,
Tom

**Comment by mblackstock** [comment]
Hi Tom,

Thanks for your note.

My node is very thin wrapper (i.e. really simple code) on the
influxdb-client 'node-influx' code here:
https://github.com/node-influx/node-influx.  That code does use the line
protocol under the hood it looks like, but it takes Javascript as
parameters.

I think understand what you mean - you want to use the line protocol in
Node-RED and use the node as a 'pass through' for that content.
Unfortunately the node-influx code is trying to make things easy for
Javascript developers, and so is converting Javascript to the line protocol
for them. I'm assuming Node-RED users want the same - to use
Javascript-object messages.

To add a 'pass through' I'd have to work around the library.  I'm not sure
this is a good idea since the protocol may change.

My thinking is that if you want to use the line protocol directly, you
could make HTTP requests using the HTTP node and format the line protocol
yourself, and skip my node.  It would probably be more work than using the
node as is!

Mike




On Thu, Jan 21, 2016 at 4:06 PM, Thomas <notifications@github.com> wrote:

> Hi Mike,
>
> first of all thank you very much for your influxd node
> I would like to ask if it is supporting the influxdb line protocol? I have
> got everything to work but only when I format the data I am sending from my
> microcontroller as JSON Then I have to put a JSON node between my receiving
> node and the influxdb node
> As I am a complete beginner it could be that I am doing something wrong
>
> Kind regards,
> Tom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mblackstock/node-red-contrib-influxdb/issues/2>.
>



-- 
*Mike Blackstock*
Chief Technical Officer
*Sense Tecnic Systems, Inc.*
308 East 5th Avenue, Vancouver, BC, V5T1H4
www.sensetecnic.com
phone: 604-760-9035 email: mblackstock@sensetecnic.com

**Comment by hl68fx** [comment]
Hi Mike,

thank you very much for your fast reply. Line protocol is not a must for me. I am just looking for an easy way to post my sensor data to influx db. I read in the influxdb documentation that they are dropping JSON support in future versions.
I am receiving a string from my sensor in my node red flow and then sending it to my influxdb node. So it would help me a lot to know how to correctly format my string for your influxdb node.
But if I am right it is ok to use the JSON format for my string because your node translates it to line protocol. So it would work also in future versions. Is that right?

Kind regards,
Tom

**Comment by mblackstock** [comment]
Hi Thomas,

I have some sample flows in the README on github page that should get you
going, and there is a small bit of documentation on the nodes themselves.
When in Node-RED you'll be dealing with message objects, not really JSON
which is a serialization format.  The examples show you how your message
objects should look https://github.com/mblackstock/node-red-contrib-influxdb.
You can paste them into your Node RED to try them out.

In your flow, you'll probably want to parse your string with a function
node, to create a message object with the fields you want to save in
influxdb.  If you put it in a format that the influx db node likes, this
saves any additional steps.

The influxdb node and library is converting these message objects to the
line protocol, so reasonably efficient :-)

Hope that helps.

Mike

**Comment by mblackstock** [comment]
Closing - to use line protocol, you can use HTTP directly as mentioned.
