### ISSUE TITLE
Multiple Tag and Retention Policies for different Fields within Batch updater

### ISSUE THREAD

**Issue by arriflex** [mblackstock/node-red-contrib-influxdb#32]
Within a single Measurement I would like to assign different Tags to Fields and hopefully also define different retention policies for individual Fields. Is this something that can be done within a single Batch update function or is it something where I have to have functions for each unique combination and then have them use the same timestamp for each to help keep the database optimized?

**Comment by mblackstock** [comment]
In a batch call you can write different points to different measurements in one go.  It's really a wrapper [on this library method](https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-method-writePoints).

I'm not sure how best to organize your data since it depends on what you want to do, but [here's a link](https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/) that outlines the different concepts in InfluxDb.  Hopefully this helps you understand the relationship between measurements, points, tags and fields, retention policies and series.  Here's more info on [schema design as well](https://docs.influxdata.com/influxdb/v1.5/concepts/schema_and_data_layout/) with some hints on do's and don'ts on how to organize your data for best performance.

I don't think you can have different retention policies for different *fields* in a measurement, but you can for different *tag* combinations on write, although I haven't tried it.  Good luck!

**Comment by arriflex** [comment]
I'm just using feeding multiple function nodes into the single batch node for now and it seems to be ok.
