### ISSUE TITLE
"Error: connect ECONNREFUSED 127.0.0.1:8086"

### ISSUE THREAD

**Issue by dubnemo** [mblackstock/node-red-contrib-influxdb#38]
I have:

1. setup Docker on a Pi3 B+
2. successfully installed InfluxDB on Docker
3. successfully created a database and user
4. successfully inserted data via Raspbian command line
5. successfully installed Node-RED on Docker
6. successfully installed node-red-contrib-influxdb
7. successfully created a simple flow using Output Node example modified to talk to localhost:8086 and my DB name

executing the flow gives the standard message that it successfully injected timestamp, whereas looking at the debug messages, I get the ECONNREFUSED message

I suspect this connection issue is related to trying to connect from the Node-RED connection which is within its own containers to InfluxDB which is a different container.

Have you ever seen this?  
Is this container to container trust?

**Comment by dubnemo** [comment]
If I use Node-RED native to Raspbian, I do not get this error message.

**Comment by mblackstock** [comment]
I think this is a docker issue.  Closing

**Comment by izanette** [comment]
To help others that might have a similar issue when using influxdb on a docker container:
If your node-red and influxdb containers are in the same machine, you can't reference it using localhost (because the host of the container is not running an influxdb itself). You need to reference it using the name of the container. 
Example: influxdb:8086 instead of localhost:8086.

**Comment by Amit2016-17** [comment]
this worked for me  --- name of database didnt work  ie influxdb  but ip of docker 172.17.0.1:8086 --worked  when using IOT stack.
two days of hardwork

**Comment by asoretmadolell** [comment]
I know it's an old issue but it did get my head spinning for a few days and this was literally the closest thing I could find to solving my problem. Hopefully someone will stumble upon it like I did and help them.

To add up on top of what @Amit2016-17 and @izanette said, yes, you do need to reference the InfluxDB container itself, but not with the container name, rather its IP address. NOT the Docker IP address. What is your container's IP address? This is how you look it up: `docker inspect <container_id> | grep IPAddress` . In my case my InfluxDB was 172.17.0.3 and my Node-RED container was 172.17.0.2. Specifying these addresses between the two solved my problem.

**Comment by gmdardengo** [comment]
> To help others that might have a similar issue when using influxdb on a docker container: If your node-red and influxdb containers are in the same machine, you can't reference it using localhost (because the host of the container is not running an influxdb itself). You need to reference it using the name of the container. Example: influxdb:8086 instead of localhost:8086.

Thank you 
using  "http://conteinerName:8080"
instead of "http://localhost:8080"
on my http request node solve my problem, now my node-red container can do a http request to another container

**Comment by donnerluetjen** [comment]
@asoretmadolell Thank you so much. This was golden advice. I spent a whole day trying to connect from container to influxdb in another container. Using the influxdb's container IP works.

**Comment by serajsersawi** [comment]
> To help others that might have a similar issue when using influxdb on a docker container: If your node-red and influxdb containers are in the same machine, you can't reference it using localhost (because the host of the container is not running an influxdb itself). You need to reference it using the name of the container. Example: influxdb:8086 instead of localhost:8086.

This worked! People like you are why I love the internet!

**Comment by Visible-Stea1th** [comment]
I setup a new docker instance last night with node-red 4.02 and influxdb 2.7.10 on Ubuntu 24.04
They are on the same netork and yet i cannot seem to get past the ECONNREFUSED error
I have tried using the IP of the influxdb container as well as the hostname.  With the hostname it just comes back as unresolved.  
Any other suggestions or places to look for info?

FWIW
I re-imaged my machine with 22.04 instead of 24.04 and ran the exact same stack.  It came up with no issues.
Perhaps there are some security features enabled or baked into 24.04,
