### ISSUE TITLE
Unable to write integer to influxDB

### ISSUE THREAD

**Issue by SleepyPrince** [mblackstock/node-red-contrib-influxdb#49]
The syntax for integer is ###i, but assigning such value in the payload would be treated as a string when passing it through the in node. Regular numeric values are treated as float in influxdb.

**Comment by Schischu** [comment]
I have the same problem. Sending the of the following payload causes a 400 error.

**Code**
```
msg.payload =  [{ 
  switch: Number(s),
  power: Number(msg.power)
},
{
  sensor: msg.id,
  name: msg.name,
  type: "lamp"
}];

return msg;
```

**Payload**
```
msg.payload : array[2]
array[2]
0: object
switch: 0
power: 4000
1: object
sensor: "27d4"
name: "P Living Room"
type: "lamp"
```

**Error**
```
message: string
Error: A 400 Bad Request error occurred: {"error":"partial write: field type conflict: input field \"power\" on measurement \"power\" is type float, already exists as type integer dropped=1"}
```

**Comment by Schischu** [comment]
After reading up a little, this is only possible by adding the option to specify schemas.
I have already a prototype change for this created only to notice that our influx version is to old. :-D
Schemas have been fixed 6 days after the version we use has been released. 
So need also to update it.

**Comment by JsBergbau** [comment]
Meanwhile influxdb 1.8 is out. Is there any update to write integer? I'm also interested in writing the values as integers, since it requires in my tests only 1/5 of storing the same data as float.

**Comment by dannutu** [comment]
I'd be interested to hear if anybody figured out how to store integers rather than floats in influxdb. Appending a "i" at the end will result in the value being stored as string rather than int. Thanks.

**Comment by mblackstock** [comment]
I've looked into this.  As mentioned in the README, these nodes wrap the [node-influx](https://github.com/node-influx/node-influx) library.  From the docs, it looks like the schema for the database needs to be [configured when instantiating an InfluxDb client](https://node-influx.github.io/class/src/index.js~InfluxDB.html).  We instantiate the InfluxDB client in the config node.  It's not clear how to specify that a value of is an integer when writing otherwise.

One approach to adding support for integers and booleans might be to create a schema configuration user interface for the config node where the user can create a list of measurements containing mapping of names to field types so the user can  specify that a field is a float, integer, string or boolean, etc..

If anyone is interested in taking this on, a PR would be welcome :-)

**Comment by dannutu** [comment]
Thanks for your answer Mike, I see now what the issue is. You mentioned:

> We instantiate the InfluxDB client in the config node.

Is this done just once upfront or every time the client needs to write something to the database? If the latter then I suppose it might be possible to pass some extra fields in the object to define the data types, e.g. if the field to write as an integer is called "temperature" then an extra field named "temperature___datatype" (or following any other naming convention) could be added; this field would specify the data type (e.g. integer or boolean). None of the extra fields following this naming convention would be actually passed to the database. And all the fields without such an extra data type field could be processed as before.  Just a silly idea, what do you think?

**Comment by mblackstock** [comment]
Currently, the InfluxDb client is instantiated when the config node is instantiated, so yes, up front. The other nodes reference this client when writing or querying the database. 
 When you create the client you specify the host, port, protocol, database, and credentials.  We could provide the schema for the measurements.  The code is pretty simple as you'll see.

We could instantiate the client every time we write I suppose, or perhaps only when we detect a schema change based on the message contents?  Not sure this is the best approach for write performance nor how the library+database will react to updates to the schema after the first one but might we worth a try.

**Comment by mblackstock** [comment]
you can now write integers using the newer APIs supported in the latest version of this node (1.8-flux and 2.0 configuration)
