### ISSUE TITLE
Influx node not useable with reverse proxy installation

### ISSUE THREAD

**Issue by loeten** [mblackstock/node-red-contrib-influxdb#70]
I have an apache2-driven webserver with a valid HTTPS certificate setup. I installed InfluxDB on this machine, in order to easily use it's https certificates by inserting into the virtualhosts/443 this lines:

```
        #influx
        ProxyPass "/influx" "http://localhost:8086"
        ProxyPassReverse "/influx" "http://localhost:8086"

```

I did so, because so I don't need to extra-care for the certificate and ~renewal for influx separately, but wanted to have https traffic for influxdb.

Now I can use it with curl, but I can't with node-red-contrib-influxdb, because it seems unable to handle the redirection / reverse proxy. More details here in this thread:

https://discourse.nodered.org/t/cant-use-influx-node-with-reverse-proxy/35948

**Comment by mblackstock** [comment]
Thanks for the feature request.  Unfortunately it doesn't look like this is something we can add to the node easily.

The official library we use in this node to communicate with InfluxDb 2.0 is the official one [@influxdata/influxdb-client](https://www.npmjs.com/package/@influxdata/influxdb-client).  From browsing their code, It doesn't look like they've implemented a follow redirect functionality in the HTTP transport, and they don't use the deprecated request module that has this built in.

So, I'm afraid this is not going to be added any time soon.  As others have suggested on the thread, perhaps you can configure the node to use the URL you're being redirected to?

Maybe try configuring the URL to be `https://********.no-ip.biz/influx:443` instead of `https://********.no-ip.biz/influx` to avoid the redirect?
