### ISSUE TITLE
Missing payload properties caused "unable to parse" error

### ISSUE THREAD

**Issue by 877dev** [mblackstock/node-red-contrib-influxdb#89]
Influxdb 1.8.4 Docker image running on Pi 4
node-red-contrib-influxdb node version 0.5.4
Node Red v1.2.6

When deploying, I'm getting influxdb "unable to parse" errors in debug. Only happens after the initial deploy, I believe this is due to the retained mqtt message not containing the full payload. In this case `msg.payload.linkquality` is missing from the mqtt payload, not sure why this is the case.

![image](https://user-images.githubusercontent.com/46575282/110356976-b21e9180-8032-11eb-82be-8cebf79f3de4.png)
![image](https://user-images.githubusercontent.com/46575282/110358100-e9417280-8033-11eb-8c14-abb1a11980e9.png)

Sample flow attached showing how the missing  `msg.payload.linkquality` causes the output to be "undefined".
![image](https://user-images.githubusercontent.com/46575282/110357990-c8791d00-8033-11eb-8672-bb42b1e5862f.png)
[flow.txt](https://github.com/mblackstock/node-red-contrib-influxdb/files/6103098/flow.txt)

**Comment by mblackstock** [comment]
I'm not sure I understand what the bug is that you are reporting.  Is it a bug in your flow, or the influxdb node?

At first glance I can see that in some cases, the field is called `linkQuality` and in the debug flow it looks like it is `linkquality` (lower case Q).  If linkQuality is a boolean in influxdb then indeed, setting it to `undefined` will throw an error.

Anyway, I don't see a problem with the influxdb node.
